# Use a Fedora bootable image as the base
FROM quay.io/fedora-ostree-desktops/silverblue:42

# Commit the base image for bootc to track changes
RUN ostree container commit

# Layer additional packages using rpm-ostree
RUN rpm-ostree install \
	stow \
	neovim \
	gvim \
	kitty \
	tmux \
	fzf \
	atuin \
	distrobox \
	openconnect \
	cifs-utils
	
# distrobox create --name nix-toolbox --image ghcr.io/thrix/nix-toolbox:42

# RUN flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# RUN flatpak install --system -y flathub \
# 	com.github.tchx84.Flatseal \
# 	org.gimp.GIMP \
# 	com.spotify.Client \
# 	com.discordapp.Discord \
# 	com.vivaldi.Vivaldi \
# 	org.mozilla.firefox \
# 	org.ferdium.Ferdium

