# Use a Fedora bootable image as the base
FROM quay.io/fedora-ostree-desktops/silverblue:42

# Commit the base image for bootc to track changes
RUN ostree container commit

RUN rpm-ostree install \
    gnome-tweaks \
	stow \
	kitty \
	distrobox \
	openconnect \
	cifs-utils \
	neovim \
	gvim \
	tmux \
	fzf \
	atuin

# TODO: Can I move from neovim down to a nix dev container withouth messing up my workflow?
