include ./theme.conf
shell_integration  no-cursor
cursor_shape block
cursor_blink_interval 0.75
enable_audio_bell no

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+enter launch --type=os-window --cwd=current
map ctrl+shift+space launch --type=overlay --title=dropdown

font_family DejaVuSansM Nerd Font Mono

symbol_map U+30A0-U+30FF Noto Sans Mono CJK JP
font_size 13.0
bold_font        auto
italic_font      auto
bold_italic_font auto
# Scale down the brightness of text (0.0 = invisible, 1.0 = full)
# dim_opacity 0.25
# window_logo_path /home/thadryan/Vaults/Home/Areas/Art/Backgrounds/rapture-modified.png
# window_logo_path /home/thadryan/Vaults/Home/Areas/Art/Backgrounds/spidey-venom.jpg
window_logo_path /home/thadryan/Vaults/Home/Areas/Art/Backgrounds/spidey-venom-low-exposure.jpg

window_logo_position center
window_logo_alpha .35
# this isn't recognized on the debian stable version :(
# window_logo_scale 100
hide_window_decorations yes
detect_mod_key_press yes

# so weird!
# cursor_trail 3
# cursor_trail_decay 0.1 0.4

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
symbol_map U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A8,U+F500-U+FD46,U+F0001-U+F1AF0 Symbols Nerd Font
copy_on_select yes
