color0 #111411
color1 #ffb4ab
color2 #85d993
color3 #b8ccb6
color4 #a1ced7
color5 #85d993
color6 #b8ccb6
color7 #e2e3dd
color8 #8b9389
color9 #ffb4ab
color10 #85d993
color11 #b8ccb6
color12 #a1ced7
color13 #85d993
color14 #b8ccb6
color15 #e2e3dd

cursor                #e2e3dd
cursor_text_color     #111411
background            #111411
foreground            #e2e3dd
selection_foreground  #c1c9be
selection_background  #414941
active_border_color   #85d993
inactive_border_color #414941
url_color             #85d993

active_tab_foreground   #003916
active_tab_background   #85d993
inactive_tab_foreground #c1c9be
inactive_tab_background #414941
cursor_trail_color      #c1c9be
