hostname_groups_enabled = true

[hostname_groups]
darlene = [
    "bases/base-arch-gnome",
    "darlene/arch/main",
    "darlene/arch/unmanaged"
]

tyrell = [
    "bases/base-tumbleweed"
]

[hostname_enabled_backends]
darlene = ["arch", "cargo", "flatpak"]
tyrell = ["zypper", "cargo", "npm"]

[arch]
package_manager = "paru"

[cargo]

# [flatpak]
# systemwide = true
